export default[
    {
        _id:"d0awy087tdaw322",
        img_src:require('../images/course-1.png'),
        heading:'Стойка на Руках Базовый Уровень',
        description:'Программа Тренировок по Гимнастике для Любителей нв 6 недель',
        target:'Цель: Стойка на руках. Укрепление мыщц Кора и Развитие Координации',
        level:'базовый',
        free:false,
        price:19,
        old_price:29,
    },
    {
        _id:"d0awydawncabwd2524",
        img_src:require('../images/course-2.png'),
        heading:'Стойка на Руках Уровеь PRO',
        description:'Программа Тренировок по Гимнастике для Любителей на 6 недель',
        target:'Стойка на Руках. Развитие Силы и Координации',
        level:'Подготовленный',
        price:19,
        free:false,
        old_price:29,
    },
    {
        _id:"d0daw6adw9d87a",
        img_src:require('../images/course-3.png'),
        heading:'Шпагат за 6 недель',
        description:'Программа Тренировок по Гимнастике для Любителей на 6 недель',
        target:'Развитие Гибкости. Освоить Шпагат.',
        level:'Базовый',
        price:19,
        free:false,
        old_price:29,
    },
    {
        _id:"camwcnaw8da5w43",
        img_src:require('../images/course-4.png'),
        heading:'Общая Физическая подготовка',
        description:'Программа Тренировок по Гимнастике для Любителей на 6 недель',
        target:'Укрпепление Тела. Снижение Веса',
        level:'Базовый',
        free:true,
        price:'',
        old_price:'',
    }
]